//! Deterministic TypeScript generation from `contracts/openapi.yaml`.
//! The YAML is the source of truth; `check` regenerates in memory and diffs.

use serde_yaml::Value;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const HEADER: &str = "/* generated by `bullet contracts generate`\n\
                      \x20* source: contracts/openapi.yaml\n\
                      \x20* regenerate: cargo run -p bullet -- contracts generate\n\
                      \x20* do not hand-edit */\n\n";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Write `contracts/generated/api.ts` from the YAML contract.
///
/// # Errors
///
/// Returns a message when the YAML is unreadable or unsupported.
pub fn generate() -> Result<(), String> {
    let out_path = repo_root().join("contracts/generated/api.ts");
    let rendered = render()?;
    std::fs::write(&out_path, rendered)
        .map_err(|err| format!("write {}: {err}", out_path.display()))?;
    println!("contracts generate: wrote {}", out_path.display());
    Ok(())
}

/// Regenerate in memory and compare with the committed file.
///
/// # Errors
///
/// Returns a message when the committed file is stale or missing.
pub fn check() -> Result<(), String> {
    let out_path = repo_root().join("contracts/generated/api.ts");
    let expected = render()?;
    let current = std::fs::read_to_string(&out_path)
        .map_err(|err| format!("read {}: {err}", out_path.display()))?;
    if current != expected {
        let diff_line = first_difference(&current, &expected);
        return Err(format!(
            "contracts/generated/api.ts is stale (first difference at line {diff_line}); \
             run `cargo run -p bullet -- contracts generate`"
        ));
    }
    println!("contracts check: up to date");
    Ok(())
}

fn first_difference(current: &str, expected: &str) -> usize {
    for (idx, (a, b)) in current.lines().zip(expected.lines()).enumerate() {
        if a != b {
            return idx + 1;
        }
    }
    current.lines().count().min(expected.lines().count()) + 1
}

fn render() -> Result<String, String> {
    let yaml_path = repo_root().join("contracts/openapi.yaml");
    let text = std::fs::read_to_string(&yaml_path)
        .map_err(|err| format!("read {}: {err}", yaml_path.display()))?;
    let doc: Value =
        serde_yaml::from_str(&text).map_err(|err| format!("parse openapi.yaml: {err}"))?;
    let schemas = doc
        .get("components")
        .and_then(|components| components.get("schemas"))
        .and_then(Value::as_mapping)
        .ok_or("openapi.yaml has no components.schemas")?;
    let mut out = String::from(HEADER);
    for (name, schema) in schemas {
        let name = name
            .as_str()
            .ok_or_else(|| format!("schema name {name:?} is not a string"))?;
        let body = ts_type(schema, 0).map_err(|err| format!("schema {name}: {err}"))?;
        writeln!(out, "export type {name} = {body};\n").map_err(|err| err.to_string())?;
    }
    out.push_str("export const API_PREFIX = \"/v1\";\n");
    Ok(out)
}

fn ts_type(schema: &Value, indent: usize) -> Result<String, String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .map(str::to_string)
            .ok_or_else(|| format!("unsupported $ref {reference}"));
    }
    if let Some(options) = schema.get("enum").and_then(Value::as_sequence) {
        let mut parts = Vec::new();
        for option in options {
            let literal = option
                .as_str()
                .ok_or_else(|| format!("non-string enum member {option:?}"))?;
            parts.push(format!("\"{literal}\""));
        }
        return Ok(parts.join(" | "));
    }
    if let Some(options) = schema.get("oneOf").and_then(Value::as_sequence) {
        let parts = options
            .iter()
            .map(|option| ts_type(option, indent))
            .collect::<Result<Vec<_>, _>>()?;
        return Ok(parts.join(" | "));
    }
    match schema.get("type") {
        Some(Value::String(kind)) => named_type(kind, schema, indent),
        Some(Value::Sequence(kinds)) => {
            let mut parts = Vec::new();
            for kind in kinds {
                let kind = kind
                    .as_str()
                    .ok_or_else(|| format!("non-string type entry {kind:?}"))?;
                parts.push(named_type(kind, schema, indent)?);
            }
            Ok(parts.join(" | "))
        }
        _ => Err("schema has no $ref, enum, oneOf, or type".into()),
    }
}

fn named_type(kind: &str, schema: &Value, indent: usize) -> Result<String, String> {
    match kind {
        "string" => Ok("string".into()),
        "integer" | "number" => Ok("number".into()),
        "boolean" => Ok("boolean".into()),
        "null" => Ok("null".into()),
        "array" => {
            let items = schema.get("items").ok_or("array schema without items")?;
            Ok(format!("{}[]", ts_type(items, indent)?))
        }
        "object" => object_type(schema, indent),
        other => Err(format!("unsupported type {other}")),
    }
}

fn object_type(schema: &Value, indent: usize) -> Result<String, String> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_mapping)
        .ok_or("object schema without properties")?;
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(Value::as_sequence)
        .map(|entries| entries.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let pad = "  ".repeat(indent);
    let mut out = String::from("{\n");
    for (prop, prop_schema) in properties {
        let prop = prop
            .as_str()
            .ok_or_else(|| format!("property name {prop:?} is not a string"))?;
        let marker = if required.contains(prop) { "" } else { "?" };
        let value = ts_type(prop_schema, indent + 1)?;
        writeln!(out, "{pad}  {prop}{marker}: {value};").map_err(|err| err.to_string())?;
    }
    write!(out, "{pad}}}").map_err(|err| err.to_string())?;
    Ok(out)
}
