// Generated by: bullet-wire-contract-tool v1alpha1
// Source: contracts/v1alpha1 + policy/v1alpha1
// Command: just contract-generate
// DO NOT EDIT BY HAND.
pub const SCHEMA_VERSION: &str = "v1alpha1";
pub const SCHEMA_BUNDLE_HASH: &str =
    "f670dd9fe8694a1f54d4be9af67ad5e62a597a28dfe664efb4471899ea77cde7";
pub const INVARIANT_REGISTRY_HASH: &str =
    "978a8b4ebb14ff0c978afb431c154647adef2f9839de322356a765c59a0c3858";
pub const POLICY_SNAPSHOT_HASH: &str =
    "78858376aaf635636a82bee274a4ff899897df834f7925a1b8c3b867313ae802";
pub const CANONICAL_GOLDEN_JSON: &str = r##"{"a":"é","array":[true,null,17],"z":"last"}"##;
pub const CANONICAL_GOLDEN_HASH: &str =
    "1d800cb94962906f78d42cb8cc84c2c078311a50e35ca515240b800abc3d2263";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PinnedContract {
    SchemaBundle,
    InvariantRegistry,
    PolicySnapshot,
    CanonicalGolden,
}

impl PinnedContract {
    fn identity(self) -> (&'static str, &'static str) {
        match self {
            Self::SchemaBundle => ("schema.bundle", SCHEMA_BUNDLE_HASH),
            Self::InvariantRegistry => ("invariant.registry", INVARIANT_REGISTRY_HASH),
            Self::PolicySnapshot => ("policy.snapshot", POLICY_SNAPSHOT_HASH),
            Self::CanonicalGolden => ("golden.cross-language", CANONICAL_GOLDEN_HASH),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ContractPinError {
    document: &'static str,
}

impl ContractPinError {
    #[must_use]
    pub const fn reason_code(&self) -> &'static str {
        "UNPINNED_CONTRACT"
    }

    #[must_use]
    pub const fn document(&self) -> &'static str {
        self.document
    }
}

impl std::fmt::Display for ContractPinError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "{} bytes do not match the pinned identity",
            self.document
        )
    }
}

impl std::error::Error for ContractPinError {}

pub fn verify_pinned_contract(
    contract: PinnedContract,
    bytes: &[u8],
) -> Result<(), ContractPinError> {
    let (domain, expected) = contract.identity();
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"bullet-wire.v1\0");
    update_frame(&mut hasher, domain.as_bytes());
    update_frame(&mut hasher, bytes);
    let actual = hasher.finalize().to_hex();
    if actual.as_str() == expected {
        Ok(())
    } else {
        Err(ContractPinError { document: domain })
    }
}

fn update_frame(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_le_bytes());
    hasher.update(bytes);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_pin_rejects_any_byte_or_domain_change() {
        verify_pinned_contract(
            PinnedContract::CanonicalGolden,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .unwrap();

        let mut changed = CANONICAL_GOLDEN_JSON.as_bytes().to_vec();
        changed.push(b' ');
        let error = verify_pinned_contract(PinnedContract::CanonicalGolden, &changed).unwrap_err();
        assert_eq!(error.reason_code(), "UNPINNED_CONTRACT");
        assert_eq!(error.document(), "golden.cross-language");
        assert!(verify_pinned_contract(
            PinnedContract::SchemaBundle,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .is_err());
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AcceptanceContractV1 {
    pub schema_version: String,
    pub contract_id: String,
    pub organization_id: String,
    pub repository_id: String,
    pub target: String,
    pub base_policy_hash: String,
    pub requirements: Vec<serde_json::Value>,
    pub risk_class: String,
    pub evidence_floor: String,
    pub oracle_resources: Vec<String>,
    pub observation_window_seconds: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActivationPointer {
    pub schema_version: String,
    pub activation_pointer_id: String,
    pub promotion_decision_id: String,
    pub policy_hash: String,
    pub recipe_id: String,
    pub provider_snapshot: String,
    pub activates_at_unix_ms: u64,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AdjudicationReceipt {
    pub schema_version: String,
    pub adjudication_receipt_id: String,
    pub attack_proposal_id: String,
    pub failure_class_id: String,
    pub decision: String,
    pub evidence_ids: Vec<String>,
    pub adjudicator: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AggregateEvaluationV1 {
    pub schema_version: String,
    pub aggregate_id: String,
    pub protocol_id: String,
    pub recipe_id: String,
    pub evaluation_ids: Vec<String>,
    pub estimands: serde_json::Value,
    pub missingness: serde_json::Value,
    pub all_in_cost: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AllocationReceiptV1 {
    pub schema_version: String,
    pub allocation_id: String,
    pub protocol_id: String,
    pub task_id: String,
    pub arm: String,
    pub seed: u64,
    pub propensity: String,
    pub eligible_set_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArchivePolicyV1 {
    pub schema_version: String,
    pub archive_policy_id: String,
    pub descriptors: Vec<serde_json::Value>,
    pub epsilon_vector: serde_json::Value,
    pub objective_directions: serde_json::Value,
    pub cell_capacity: u64,
    pub reference_points: serde_json::Value,
    pub tie_breaks: serde_json::Value,
    pub reevaluation_policy: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AttackProposal {
    pub schema_version: String,
    pub attack_proposal_id: String,
    pub recipe_id: String,
    pub target_hash: String,
    pub proposal: serde_json::Value,
    pub proposer_class: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AuditBatchV1 {
    pub schema_version: String,
    pub audit_batch_id: String,
    pub first_sequence: u64,
    pub last_sequence: u64,
    pub previous_root: String,
    pub merkle_root: String,
    pub signer: String,
    pub external_anchor_receipt: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BehaviorTraceV1 {
    pub schema_version: String,
    pub trace_id: String,
    pub recipe_id: String,
    pub task_id: String,
    pub events: Vec<serde_json::Value>,
    pub environment_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CandidateManifestV1 {
    pub schema_version: String,
    pub candidate_id: String,
    pub repository_id: String,
    pub target: String,
    pub base_oid: String,
    pub head_oid: String,
    pub tree_oid: String,
    pub patch_digest: String,
    pub actual_scope: Vec<String>,
    pub granted_scope: Vec<String>,
    pub attempt_id: String,
    pub attempt_fence: u64,
    pub graph_revision_id: String,
    pub policy_hash: String,
    pub config_hash: String,
    pub route_hash: String,
    pub environment_hash: String,
    pub toolchain_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CertificationKey {
    pub schema_version: String,
    pub certification_key_id: String,
    pub recipe_id: String,
    pub policy_hash: String,
    pub task_stratum: String,
    pub risk_stratum: String,
    pub provider: String,
    pub model: String,
    pub adapter: String,
    pub profile: String,
    pub toolchain_hash: String,
    pub environment_hash: String,
    pub evaluator_hash: String,
    pub corpus_hash: String,
    pub schema_hash: String,
    pub observation_policy_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CertificationRecord {
    pub schema_version: String,
    pub certification_record_id: String,
    pub certification_key_id: String,
    pub decision: String,
    pub evidence_ids: Vec<String>,
    pub expires_at_unix_ms: u64,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CheckIntentV1 {
    pub schema_version: String,
    pub check_intent_id: String,
    pub exact_sha: String,
    pub target: String,
    pub proof_bundle_id: String,
    pub attestor_policy_hash: String,
    pub expected_prior_check: String,
    pub reconciliation_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContaminationDecision {
    pub schema_version: String,
    pub contamination_decision_id: String,
    pub exposure_edge_ids: Vec<String>,
    pub decision: String,
    pub reason_code: String,
    pub reviewer: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecertificationReceipt {
    pub schema_version: String,
    pub decertification_receipt_id: String,
    pub certification_record_id: String,
    pub drift_signal_id: String,
    pub effective_at_unix_ms: u64,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DelayedOutcomeLink {
    pub schema_version: String,
    pub delayed_outcome_link_id: String,
    pub route_decision_id: String,
    pub observation_id: String,
    pub survival_outcome: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryGrantV1 {
    pub schema_version: String,
    pub delivery_grant_id: String,
    pub candidate_id: String,
    pub proof_bundle_id: String,
    pub authority_envelope_digest: String,
    pub expires_at_unix_ms: u64,
    pub grant_nonce: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DriftSignal {
    pub schema_version: String,
    pub drift_signal_id: String,
    pub system_fingerprint_id: String,
    pub drift_kind: String,
    pub evidence: serde_json::Value,
    pub required_action: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EffectIntentV1 {
    pub schema_version: String,
    pub effect_intent_id: String,
    pub effect_kind: String,
    pub endpoint_identity: String,
    pub logical_key: String,
    pub desired_state_hash: String,
    pub expected_state_hash: String,
    pub candidate_id: String,
    pub proof_bundle_id: String,
    pub policy_hash: String,
    pub authority_epoch: u64,
    pub freeze_generation: u64,
    pub expires_at_unix_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvaluationVectorV1 {
    pub schema_version: String,
    pub evaluation_id: String,
    pub task_id: String,
    pub recipe_id: String,
    pub candidate_id: String,
    pub objectives: serde_json::Value,
    pub costs: serde_json::Value,
    pub outcome: String,
    pub closure_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidenceV1 {
    pub schema_version: String,
    pub evidence_id: String,
    pub candidate_id: String,
    pub subject_hash: String,
    pub outcome: String,
    pub tier: String,
    pub reason_code: String,
    pub verifier_principal: String,
    pub environment_hash: String,
    pub custody: serde_json::Value,
    pub started_at_unix_ms: u64,
    pub completed_at_unix_ms: u64,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExperimentProtocolV1 {
    pub schema_version: String,
    pub protocol_id: String,
    pub hypotheses: Vec<String>,
    pub estimands: Vec<String>,
    pub arms: Vec<serde_json::Value>,
    pub randomization_unit: String,
    pub blocking: serde_json::Value,
    pub power: serde_json::Value,
    pub multiplicity: serde_json::Value,
    pub missingness: serde_json::Value,
    pub stopping_rule: serde_json::Value,
    pub budgets: serde_json::Value,
    pub interference_domains: serde_json::Value,
    pub review_policy: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExposureEdge {
    pub schema_version: String,
    pub exposure_edge_id: String,
    pub source: String,
    pub destination: String,
    pub exposure_kind: String,
    pub recorded_at_unix_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FailureClass {
    pub schema_version: String,
    pub failure_class_id: String,
    pub taxonomy_version: String,
    pub class_name: String,
    pub definition: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GateReceiptV1 {
    pub schema_version: String,
    pub gate_receipt_id: String,
    pub gate: String,
    pub gate_version: String,
    pub repository_commits: Vec<serde_json::Value>,
    pub policy_hash: String,
    pub schema_hash: String,
    pub toolchain_hash: String,
    pub executed_tests: Vec<String>,
    pub artifacts: Vec<serde_json::Value>,
    pub result: String,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GraphDeltaV1 {
    pub schema_version: String,
    pub graph_revision_id: String,
    pub parent_graph_revision_id: String,
    pub graph_sequence: u64,
    pub operations: Vec<serde_json::Value>,
    pub materialization_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HoldoutLease {
    pub schema_version: String,
    pub holdout_lease_id: String,
    pub holdout_suite_id: String,
    pub principal: String,
    pub query_budget: u64,
    pub expires_at_unix_ms: u64,
    pub nonce: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HoldoutSuiteManifest {
    pub schema_version: String,
    pub holdout_suite_id: String,
    pub custody_class: String,
    pub suite_hash: String,
    pub query_budget: u64,
    pub response_policy: String,
    pub retires_at_unix_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HumanDecision {
    pub schema_version: String,
    pub human_decision_id: String,
    pub principal: String,
    pub decision: String,
    pub subject_hash: String,
    pub mfa_class: String,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IntegrationIntentV1 {
    pub schema_version: String,
    pub integration_intent_id: String,
    pub protected_target: String,
    pub expected_target_oid: String,
    pub required_checks: Vec<String>,
    pub required_reviews: Vec<String>,
    pub merge_policy: String,
    pub proof_bundle_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InterventionV1 {
    pub schema_version: String,
    pub intervention_id: String,
    pub evidence_ids: Vec<String>,
    pub allowed_actions: Vec<String>,
    pub owner: String,
    pub expires_at_unix_ms: u64,
    pub resolution_receipt_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LaunchGrantV1 {
    pub schema_version: String,
    pub authority_envelope_digest: String,
    pub provider: String,
    pub profile: String,
    pub binary_digest: String,
    pub sandbox_manifest: serde_json::Value,
    pub gate_ids: Vec<String>,
    pub budget_reservation: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ObservationV1 {
    pub schema_version: String,
    pub observation_id: String,
    pub value_class: String,
    pub source: String,
    pub window_seconds: u64,
    pub observed_at_unix_ms: u64,
    pub fresh_until_unix_ms: u64,
    pub subject_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OpponentSetSnapshot {
    pub schema_version: String,
    pub opponent_set_snapshot_id: String,
    pub current_recipe_ids: Vec<String>,
    pub historical_recipe_ids: Vec<String>,
    pub oracle_hash: String,
    pub frozen_at_unix_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OverrideReceipt {
    pub schema_version: String,
    pub override_receipt_id: String,
    pub human_decision_id: String,
    pub scope: String,
    pub expires_at_unix_ms: u64,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlanRevisionV1 {
    pub schema_version: String,
    pub plan_revision_id: String,
    pub parent_revision_id: String,
    pub contract_id: String,
    pub content_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PolicySnapshotV1 {
    pub schema_version: String,
    pub policy_generation: u64,
    pub invariant_registry_hash: String,
    pub schema_bundle_hash: String,
    pub risk_policy: serde_json::Value,
    pub evidence_policy: serde_json::Value,
    pub sandbox_policy: serde_json::Value,
    pub budget_policy: serde_json::Value,
    pub issuer_keys: Vec<serde_json::Value>,
    pub activation_at_unix_ms: u64,
    pub expires_at_unix_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PromotionDecision {
    pub schema_version: String,
    pub promotion_decision_id: String,
    pub certification_record_id: String,
    pub stage: String,
    pub decision: String,
    pub review_receipt_ids: Vec<String>,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProofBundleV1 {
    pub schema_version: String,
    pub proof_bundle_id: String,
    pub candidate_id: String,
    pub evidence_ids: Vec<String>,
    pub review_ids: Vec<String>,
    pub policy_hash: String,
    pub exposure_ids: Vec<String>,
    pub audit_hash: String,
    pub proof_root: String,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct QueryIntent {
    pub schema_version: String,
    pub query_intent_id: String,
    pub holdout_lease_id: String,
    pub subject_hash: String,
    pub request_hash: String,
    pub query_ordinal: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct QueryReceipt {
    pub schema_version: String,
    pub query_receipt_id: String,
    pub query_intent_id: String,
    pub outcome_class: String,
    pub response_hash: String,
    pub budget_consumed: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReviewerAssignment {
    pub schema_version: String,
    pub reviewer_assignment_id: String,
    pub candidate_id: String,
    pub reviewer_principal: String,
    pub independence_class: String,
    pub seed: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReviewReceipt {
    pub schema_version: String,
    pub review_receipt_id: String,
    pub reviewer_assignment_id: String,
    pub decision: String,
    pub reason_code: String,
    pub subject_hash: String,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RouteDecision {
    pub schema_version: String,
    pub route_decision_id: String,
    pub route_request_id: String,
    pub selected_arm: String,
    pub excluded_arms: Vec<String>,
    pub incumbent_reserve: String,
    pub propensity: String,
    pub reservation: serde_json::Value,
    pub policy_hash: String,
    pub abstention_reason: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RouteRequest {
    pub schema_version: String,
    pub route_request_id: String,
    pub task_id: String,
    pub pretreatment_context: Vec<serde_json::Value>,
    pub eligible_arms: Vec<String>,
    pub policy_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RouterUpdateBatch {
    pub schema_version: String,
    pub router_update_batch_id: String,
    pub delayed_outcome_link_ids: Vec<String>,
    pub prior_router_hash: String,
    pub new_router_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SanitizationReceipt {
    pub schema_version: String,
    pub sanitization_receipt_id: String,
    pub attack_proposal_id: String,
    pub decision: String,
    pub removed_capabilities: Vec<String>,
    pub reviewer: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ScopeGrantV1 {
    pub schema_version: String,
    pub scope_grant_id: String,
    pub scope_revision: u64,
    pub normalized_paths: Vec<String>,
    pub protected_resources: Vec<String>,
    pub envelope_class: String,
    pub scope_digest: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SentinelResult {
    pub schema_version: String,
    pub sentinel_result_id: String,
    pub system_fingerprint_id: String,
    pub task_id: String,
    pub outcome: String,
    pub metrics: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignedAuthorityEnvelopeV1 {
    pub schema_version: String,
    pub issuer: String,
    pub audience: String,
    pub operation: String,
    pub subject_principal: String,
    pub organization_id: String,
    pub repository_id: String,
    pub mission_id: String,
    pub contract_id: String,
    pub plan_revision_id: String,
    pub graph_sequence: u64,
    pub work_package_id: String,
    pub selection_group_id: String,
    pub variant_id: String,
    pub attempt_id: String,
    pub attempt_fence: u64,
    pub runner_id: String,
    pub runner_epoch: u64,
    pub workspace_id: String,
    pub workspace_nonce: String,
    pub scope_grant_digest: String,
    pub scope_revision: u64,
    pub context_revision: u64,
    pub config_hash: String,
    pub policy_hash: String,
    pub routing_hash: String,
    pub provider: String,
    pub model: String,
    pub adapter: String,
    pub profile: String,
    pub credential_generation: u64,
    pub authority_epoch: u64,
    pub freeze_generation: u64,
    pub request_digest: String,
    pub issued_at_unix_ms: u64,
    pub not_before_unix_ms: u64,
    pub expires_at_unix_ms: u64,
    pub token_nonce: String,
    pub key_id: String,
    pub algorithm: String,
    pub signature: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SystemFingerprint {
    pub schema_version: String,
    pub system_fingerprint_id: String,
    pub recipe_hash: String,
    pub policy_hash: String,
    pub provider_hash: String,
    pub toolchain_hash: String,
    pub environment_hash: String,
    pub evaluator_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TaskCorpusManifestV1 {
    pub schema_version: String,
    pub corpus_id: String,
    pub selection_frame: String,
    pub inclusion_policy: String,
    pub exclusion_policy: String,
    pub task_ids: Vec<String>,
    pub strata: Vec<serde_json::Value>,
    pub clusters: Vec<serde_json::Value>,
    pub sample_weights: serde_json::Value,
    pub exposure_policy: serde_json::Value,
    pub partitions: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TaskSpecV1 {
    pub schema_version: String,
    pub task_id: String,
    pub repository_id: String,
    pub base_oid: String,
    pub target: String,
    pub acceptance_hash: String,
    pub observation_window_seconds: u64,
    pub task_family: String,
    pub visible_features: Vec<serde_json::Value>,
    pub risk_class: String,
    pub evidence_floor: String,
    pub stratum: String,
    pub lineage_cluster: String,
    pub contamination_group: String,
    pub environment_requirements: Vec<String>,
    pub invalidity_rule: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TeamRecipeV1 {
    pub schema_version: String,
    pub recipe_id: String,
    pub topology: String,
    pub roles: Vec<serde_json::Value>,
    pub edges: Vec<serde_json::Value>,
    pub budgets: serde_json::Value,
    pub policy_hash: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerificationIntentV1 {
    pub schema_version: String,
    pub verification_intent_id: String,
    pub candidate_id: String,
    pub candidate_closure_hash: String,
    pub gate_ids: Vec<String>,
    pub oracle_manifest_ids: Vec<String>,
    pub exposure_manifest_ids: Vec<String>,
    pub required_tier: String,
    pub verifier_audience: String,
}
